Test/exercise endpoints
SE310-Team-1/SE310_Fitness_Tracker pull request #25
Opened 2024-08-13 13:17 UTC by chrisv09

Added five tests:
- Getting one exercise by name, date and set
- Getting all exercises
- Getting the full exercise history
- Getting all the exercises on a given day

- Getting all the workouts

I also added a package to help us use env files across different OSs.

Remember to npm install after squash + merge!

2024-08-14 06:17 UTC, joh748 requested changes

2024-08-14 11:37 UTC, chrisv09 commented on server/controllers/exercises-controller.js
> +    exerciseByNameDateAndSets
Fixed!

2024-08-14 15:17 UTC, joh748 submitted a review, later dismissed
otherwise, it looks good to me

2024-08-15 02:26 UTC, tom1dev approved these changes
looks good to me

2024-08-15 10:04 UTC, LX6T approved these changes
very good very good

2024-08-15 21:52 UTC, joh748 approved these changes
looks good to me

2024-08-15 22:10 UTC, merged